/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Isra Khan
 */
public class TestMain extends javax.swing.JFrame {

    /**
     * Creates new form TestMain
     */
    public TestMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdmissionLabel = new javax.swing.JLabel();
        FacultyButton = new javax.swing.JButton();
        DepartmentButton = new javax.swing.JButton();
        ProgramButton = new javax.swing.JButton();
        UniversityofSindhLabel = new javax.swing.JLabel();
        BatchButton = new javax.swing.JButton();
        StudentButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AdmissionLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        AdmissionLabel.setText("Admission System         ");
        getContentPane().add(AdmissionLabel);
        AdmissionLabel.setBounds(47, 11, 566, 58);

        FacultyButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        FacultyButton.setText("Faculty");
        FacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FacultyButton);
        FacultyButton.setBounds(220, 150, 107, 40);

        DepartmentButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        DepartmentButton.setText("Department");
        getContentPane().add(DepartmentButton);
        DepartmentButton.setBounds(220, 210, 107, 40);

        ProgramButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        ProgramButton.setText("Program");
        ProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ProgramButton);
        ProgramButton.setBounds(220, 260, 107, 40);

        UniversityofSindhLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        UniversityofSindhLabel.setText("University of Sindh");
        getContentPane().add(UniversityofSindhLabel);
        UniversityofSindhLabel.setBounds(39, 75, 457, 58);

        BatchButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        BatchButton.setText("Batch");
        getContentPane().add(BatchButton);
        BatchButton.setBounds(220, 310, 107, 40);

        StudentButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        StudentButton.setText("Student");
        getContentPane().add(StudentButton);
        StudentButton.setBounds(220, 360, 107, 40);

        ExitButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ExitButton.setText("Exit");
        getContentPane().add(ExitButton);
        ExitButton.setBounds(220, 410, 107, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramButtonActionPerformed

    private void FacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyButtonActionPerformed
        
        FacultyFrame ob=new FacultyFrame();
        ob.show();
    }//GEN-LAST:event_FacultyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdmissionLabel;
    private javax.swing.JButton BatchButton;
    private javax.swing.JButton DepartmentButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton FacultyButton;
    private javax.swing.JButton ProgramButton;
    private javax.swing.JButton StudentButton;
    private javax.swing.JLabel UniversityofSindhLabel;
    // End of variables declaration//GEN-END:variables
}
